import * as THREE from './three.module.min.js';

// Pon el MP3 autorizado en /audio/cancion.mp3. Cuando elijas el clímax, cambia null por el segundo exacto.
const MUSIC_CONFIG={src:'audio/cancion.mp3',volume:.40,supernovaTimestamp:null};
const data=[
['sol','SOL','LUZ','Hay personas que tienen una forma especial de iluminar los días sin siquiera intentarlo. Tú eres una de ellas.','Y este universo tenía que comenzar con un poquito de esa luz.',0,4.2,'#ff9c28'],
['mercurio','MERCURIO','COINCIDENCIAS','A veces uno conoce personas sin imaginar todo lo bonito que después va a compartir con ellas. Qué bueno que un día coincidimos.','Algunas coincidencias terminan convirtiéndose en bonitos recuerdos.',8,1.0,'#aaa7a1'],
['venus','VENUS','ESENCIA','Por esas risas que aparecen de la nada, las conversaciones y esa forma tuya de hacer especial hasta un momento sencillo.','Nunca pierdas esa esencia tan tuya.',11,1.45,'#eadcb4'],
['tierra','TIERRA','COINCIDIR','Entre tantas personas, lugares y momentos… qué bonito fue coincidir contigo justo aquí.','Gracias por tu amistad y por cada pequeño momento que se ha ido convirtiendo en recuerdo.',15,1.65,'#287ec4'],
['marte','MARTE','FUERZA','Quizá no todos los días sean fáciles, pero nunca olvides todo lo que eres capaz de superar.','Sigue adelante, incluso cuando el camino se ponga complicado.',19,1.25,'#a96743'],
['jupiter','JÚPITER','SUEÑOS','Que tus sueños siempre sean más grandes que aquello que alguna vez te hizo dudar.','Todavía quedan muchísimas cosas bonitas por descubrir.',25,2.75,'#c9b69b'],
['saturno','SATURNO','RECUERDOS','Al final, la vida también está hecha de pequeños momentos que algún día terminamos recordando con una sonrisa.','Gracias por algunos de esos momentos.',31,2.35,'#d8c99e'],
['urano','URANO','LIBERTAD','Nunca dejes de elegir tu propio camino, cambiar, descubrir y convertirte en quien tú quieras ser.','Este universo no tiene caminos obligatorios. El tuyo tampoco.',37,1.9,'#a9d9de'],
['neptuno','NEPTUNO','LO QUE VIENE','No sabemos qué traerán los próximos capítulos, pero ojalá estén llenos de lugares, personas y momentos que te hagan feliz.','Que la vida todavía tenga muchas sorpresas bonitas guardadas para ti.',43,1.85,'#5c7fb6']
];
const canvas=document.querySelector('#universe'),app=document.querySelector('#app'),cover=document.querySelector('#cover'),panel=document.querySelector('#planetPanel'),secret=document.querySelector('#secret'),lunarSecret=document.querySelector('#lunarSecret'),final=document.querySelector('#final'),supernova=document.querySelector('#supernova'),labels=document.querySelector('#orbitLabels'),progress=document.querySelector('#progress'),audio=document.querySelector('#soundtrack');
const screenQuery=matchMedia('(max-width:700px),(pointer:coarse)');
let compactScreen=screenQuery.matches;
audio.src=MUSIC_CONFIG.src;let active=false,selected=null,visited=new Set(),plutoReady=false,ending=false,lastRender=0;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,250),renderer=new THREE.WebGLRenderer({canvas,antialias:!compactScreen,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,compactScreen?1.2:1.6));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor(0x080604);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;camera.position.set(0,18,64);
const solar=new THREE.Group();scene.add(solar);new THREE.TextureLoader().load('images/nebula-cinematic.webp',t=>{t.colorSpace=THREE.SRGBColorSpace;scene.background=t});const stars=new THREE.BufferGeometry(),pts=[];for(let i=0;i<(compactScreen?720:1300);i++){let r=60+Math.random()*110,a=Math.random()*6.28,z=(Math.random()-.5)*130;pts.push(Math.cos(a)*r,z,Math.sin(a)*r)}stars.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0xffe8c7,size:.32,transparent:true,opacity:.82,sizeAttenuation:true})));
scene.add(new THREE.AmbientLight(0x674521,1.8));const sunLight=new THREE.PointLight(0xffb45f,210,130,2);scene.add(sunLight);const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),worlds=[];let moonMesh=null,moonHit=null,moonHalo=null,moonActive=false,moonReturning=false,moonState=null;
function tex(id,color){let c=document.createElement('canvas');c.width=512;c.height=256;let x=c.getContext('2d'),g=x.createLinearGradient(0,0,512,256);g.addColorStop(0,'#291127');g.addColorStop(.12,color);g.addColorStop(.5,color);g.addColorStop(.88,color);g.addColorStop(1,'#210d25');x.fillStyle=g;x.fillRect(0,0,512,256);let crater=()=>{for(let i=0;i<42;i++){let px=Math.random()*512,py=18+Math.random()*220,rr=2+Math.random()*12;x.fillStyle='rgba(37,20,26,.3)';x.beginPath();x.arc(px,py,rr,0,7);x.fill();x.strokeStyle='rgba(255,222,184,.18)';x.lineWidth=1;x.stroke()}};if(id==='mercurio'||id==='marte'||id==='pluto')crater();if(id==='jupiter'||id==='saturno'||id==='urano'||id==='neptuno'){for(let i=0;i<72;i++){let y=Math.random()*256,h=2+Math.random()*10;x.fillStyle=id==='neptuno'?'rgba(133,210,255,.14)':id==='urano'?'rgba(235,255,255,.17)':'rgba(255,235,204,.16)';x.fillRect(0,y,512,h)}if(id==='jupiter'){x.fillStyle='rgba(135,52,32,.58)';x.beginPath();x.ellipse(325,158,46,20,0,0,7);x.fill()}if(id==='neptuno'){x.fillStyle='rgba(202,238,255,.52)';x.beginPath();x.ellipse(340,92,30,12,0,0,7);x.fill()}}if(id==='venus'){for(let i=0;i<58;i++){x.strokeStyle=`rgba(255,235,188,${.12+Math.random()*.2})`;x.lineWidth=2+Math.random()*7;x.beginPath();let y=Math.random()*256;x.moveTo(0,y);x.bezierCurveTo(110,y-25,360,y+28,512,y-8);x.stroke()}}if(id==='tierra'){for(let i=0;i<36;i++){x.fillStyle=`rgba(75,174,91,${.58+Math.random()*.3})`;x.beginPath();x.ellipse(Math.random()*512,30+Math.random()*190,12+Math.random()*38,5+Math.random()*16,Math.random()*3,0,7);x.fill()}for(let i=0;i<28;i++){x.fillStyle='rgba(255,255,255,.48)';x.fillRect(Math.random()*512,Math.random()*256,25+Math.random()*85,2+Math.random()*3)}}let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function sunTex(){let c=document.createElement('canvas');c.width=512;c.height=256;let x=c.getContext('2d'),g=x.createLinearGradient(0,0,512,256);g.addColorStop(0,'#c54d1f');g.addColorStop(.25,'#f9822b');g.addColorStop(.5,'#ffc65e');g.addColorStop(.75,'#f57b29');g.addColorStop(1,'#bd461f');x.fillStyle=g;x.fillRect(0,0,512,256);for(let i=0;i<360;i++){let px=Math.random()*512,py=Math.random()*256,rr=2+Math.random()*11;x.fillStyle=`rgba(255,${150+Math.random()*100|0},${40+Math.random()*100|0},${.1+Math.random()*.28})`;x.beginPath();x.ellipse(px,py,rr*1.6,rr,Math.random()*3,0,7);x.fill()}for(let i=0;i<70;i++){x.strokeStyle='rgba(255,243,172,.2)';x.lineWidth=1+Math.random()*2;x.beginPath();let px=Math.random()*512,py=Math.random()*256;x.arc(px,py,8+Math.random()*32,0,Math.PI*1.4);x.stroke()}let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function glowTex(){let c=document.createElement('canvas');c.width=c.height=256;let x=c.getContext('2d'),g=x.createRadialGradient(128,128,2,128,128,128);g.addColorStop(0,'rgba(255,252,210,.96)');g.addColorStop(.18,'rgba(255,180,56,.72)');g.addColorStop(.52,'rgba(255,101,32,.22)');g.addColorStop(1,'rgba(255,80,25,0)');x.fillStyle=g;x.fillRect(0,0,256,256);return new THREE.CanvasTexture(c)}
const orbitLines=[];function ring(r){let p=[];for(let i=0;i<=90;i++){let a=i/90*6.283;p.push(new THREE.Vector3(Math.cos(a)*r,0,Math.sin(a)*r))}let line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),new THREE.LineBasicMaterial({color:0xffc28a,transparent:true,opacity:.17}));orbitLines.push(line);scene.add(line)}
function saturnRingTex(){let c=document.createElement('canvas');c.width=512;c.height=32;let x=c.getContext('2d');for(let i=0;i<512;i++){let a=.12+Math.random()*.62;x.fillStyle=`rgba(255,${190+Math.random()*55|0},${120+Math.random()*90|0},${a})`;x.fillRect(i,0,1,32)}return new THREE.CanvasTexture(c)}
data.forEach((d,i)=>{let [id,name,theme,text,subtext,r,size,color]=d,segments=compactScreen?[28,20]:[42,32],geo=new THREE.SphereGeometry(size,...segments),surface=id==='sol'?sunTex():tex(id,color),mat=new THREE.MeshStandardMaterial({map:surface,emissiveMap:id==='sol'?surface:null,roughness:id==='sol'?.42:.6,metalness:.04,emissive:id==='sol'?0xffac5c:new THREE.Color(color).multiplyScalar(.22),emissiveIntensity:id==='sol'?.84:.46});let mesh=new THREE.Mesh(geo,mat);let w={id,name,theme,text,subtext,r,size,mesh,angle:i*.75};if(id==='sol'){mesh.scale.setScalar(1);let halo=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex(),transparent:true,opacity:.62,depthWrite:false,blending:THREE.AdditiveBlending}));halo.scale.set(20,20,1);mesh.add(halo);solar.add(mesh)}else{let aura=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex(),color:new THREE.Color(color),transparent:true,opacity:id==='tierra'?.08:.18,depthWrite:false,blending:THREE.AdditiveBlending}));aura.scale.set(size*2.5,size*2.5,1);mesh.add(aura);ring(r);if(id==='tierra'){let moonOrbit=new THREE.Group(),moon=new THREE.Mesh(new THREE.SphereGeometry(size*.15,compactScreen?18:28,compactScreen?14:22),new THREE.MeshBasicMaterial({map:tex('luna','#d5d2ca'),color:0xe6e2d8}));moon.position.set(size*1.52,size*.16,0);let hit=new THREE.Mesh(new THREE.SphereGeometry(size*.28,16,12),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,colorWrite:false}));moon.add(hit);moonOrbit.rotation.x=.36;moonOrbit.add(moon);mesh.add(moonOrbit);w.moonOrbit=moonOrbit;w.moon=moon;moonMesh=moon;moonHit=hit}if(id==='saturno'){let ringSegments=compactScreen?72:128,rg=new THREE.RingGeometry(size*1.3,size*2.2,ringSegments),rm=new THREE.MeshBasicMaterial({map:saturnRingTex(),color:0xffe0af,transparent:true,opacity:.82,side:THREE.DoubleSide,depthWrite:false});let rr=new THREE.Mesh(rg,rm);rr.rotation.x=Math.PI/2.5;mesh.add(rr);let inner=new THREE.Mesh(new THREE.RingGeometry(size*1.42,size*1.56,ringSegments),new THREE.MeshBasicMaterial({map:saturnRingTex(),color:0xfff0cd,transparent:true,opacity:.45,side:THREE.DoubleSide,depthWrite:false}));inner.rotation.x=Math.PI/2.5;mesh.add(inner)}solar.add(mesh)}worlds.push(w)});
if(moonMesh){moonHalo=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex(),color:0xe8edf2,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));moonHalo.scale.set(.95,.95,1);moonMesh.add(moonHalo)}
const pluto={id:'pluto',name:'PLUTÓN',theme:'EL ÚLTIMO SECRETO',text:'Si llegaste hasta aquí, significa que recorriste todo este pequeño universo.',subtext:'Pero todavía faltaba algo. Porque quizá no hacía falta esperar una fecha especial para recordarte algo sencillo…',r:53,size:.8,angle:2.4,mesh:new THREE.Mesh(new THREE.SphereGeometry(.8,24,18),new THREE.MeshStandardMaterial({map:tex('pluto','#c7aa8c'),roughness:1})),hidden:true};pluto.mesh.visible=false;solar.add(pluto.mesh);worlds.push(pluto);solar.visible=false;
data.forEach((d)=>{let el=document.createElement('button');el.type='button';el.className='label';el.dataset.id=d[0];el.innerHTML=`${d[1]}<small>${d[2][0]+d[2].slice(1).toLowerCase()}</small>`;el.onclick=()=>show(worlds.find(w=>w.id===d[0]));labels.append(el)});
const mainWorlds=data.slice(1).map(d=>d[0]);
const itinerary=['mercurio','venus','tierra','marte','jupiter','saturno','urano','neptuno'];
function nextWorld(exceptId=''){return worlds.find(w=>w.id===itinerary.find(id=>id!==exceptId&&!visited.has(id)))}
function updateProgress(){let count=mainWorlds.filter(id=>visited.has(id)).length;progress.innerHTML=`<span>MUNDOS<br><b>${count} / ${mainWorlds.length}</b></span><div class="progress-orbits">${mainWorlds.map(id=>`<svg class="progress-dot ${visited.has(id)?'done':''}" viewBox="0 0 12 12" aria-hidden="true"><circle cx="6" cy="6" r="5"/><circle class="core" cx="6" cy="6" r="1.5"/></svg>`).join('')}</div>`}
function unlockPluto(){if(plutoReady)return;plutoReady=true;pluto.hidden=false;pluto.mesh.visible=true;secret.hidden=false;let el=document.createElement('button');el.type='button';el.className='label pluto-label';el.dataset.id='pluto';el.innerHTML='PLUTÓN<small>Último mundo</small>';el.onclick=()=>show(pluto);labels.append(el);updateProgress()}
const musicButton=document.querySelector('#music'),exploreButton=document.querySelector('#explore');
let fadeFrame=0,fadeVersion=0,musicAction=0;
function setMusic(){let paused=audio.paused;musicButton.innerHTML=`<svg class="sound-wave ${paused?'paused':'playing'}" viewBox="0 0 32 24" aria-hidden="true"><path d="M3 12h2M8 8v8M13 4v16M18 7v10M23 3v18M28 9v6"/></svg><small>MÚSICA<br>${paused?'OFF':'ON'}</small>`;musicButton.setAttribute('aria-label',paused?'Activar música':'Pausar música')}
function fade(v,t=850){cancelAnimationFrame(fadeFrame);let version=++fadeVersion,s=audio.volume,a=performance.now();function step(n){if(version!==fadeVersion)return;let p=Math.min(1,(n-a)/t);audio.volume=s+(v-s)*p;if(p<1)fadeFrame=requestAnimationFrame(step)}fadeFrame=requestAnimationFrame(step)}
function preloadJourney(){let names=['sol-luz','venus-esencia','tierra-coincidir','marte-fuerza','saturno-recuerdos','neptuno-futuro','final-flores'],load=deadline=>{while(names.length&&(!deadline||deadline.timeRemaining()>4)){let image=new Image();image.decoding='async';image.src=`images/${names.shift()}.webp`}if(names.length)setTimeout(()=>load(),180)};if('requestIdleCallback'in window)requestIdleCallback(load,{timeout:900});else setTimeout(()=>load(),120)}
exploreButton.onclick=async()=>{if(active)return;active=true;solar.visible=true;cover.classList.add('hidden');labels.classList.add('ready');preloadJourney();try{await audio.play();fade(MUSIC_CONFIG.volume,1200)}catch{}setMusic();setTimeout(()=>show(worlds[0]),850)};musicButton.onclick=async()=>{let action=++musicAction;if(audio.paused){await audio.play().catch(()=>{});if(!audio.paused)fade(MUSIC_CONFIG.volume)}else{fade(0,400);setTimeout(()=>{if(action===musicAction){audio.pause();setMusic()}},420)}setTimeout(setMusic,450)};
const ornaments={sol:'<svg viewBox="0 0 64 32"><circle cx="32" cy="16" r="2"/><path d="M32 2v7M32 23v7M18 16h7M39 16h7M22 6l5 6M42 6l-5 6"/></svg>',mercurio:'<svg viewBox="0 0 64 32"><path d="M5 25C19 4 27 5 32 16S46 28 59 7"/><circle cx="32" cy="16" r="2"/></svg>',venus:'<svg viewBox="0 0 64 32"><path d="M32 29V10M32 17c-8-1-11-5-12-10 8 0 11 4 12 10Zm0 5c8-1 12-5 13-10-8 0-12 4-13 10Z"/><circle cx="32" cy="7" r="3"/></svg>',tierra:'<svg viewBox="0 0 64 32"><ellipse cx="27" cy="16" rx="21" ry="8" transform="rotate(-12 27 16)"/><ellipse cx="37" cy="16" rx="21" ry="8" transform="rotate(12 37 16)"/><circle cx="32" cy="16" r="2"/></svg>',marte:'<svg viewBox="0 0 64 32"><path d="M5 25h17l6-9 5 4L43 7h16"/><path d="M27 16l5-5" opacity=".35"/></svg>',jupiter:'<svg viewBox="0 0 64 32"><circle cx="32" cy="16" r="2"/><circle cx="32" cy="16" r="7" opacity=".6"/><circle cx="32" cy="16" r="13" opacity=".3"/></svg>',saturno:'<svg viewBox="0 0 64 32"><path d="M8 19c8-9 39-12 48-4M11 23c12-7 34-8 44-2M17 27c10-4 24-4 32-1"/></svg>',urano:'<svg viewBox="0 0 64 32"><path d="M7 26c12-1 18-8 25-19M32 7c5 9 12 14 25 14M32 7c-1 10 1 16 9 22"/></svg>',neptuno:'<svg viewBox="0 0 64 32"><path d="M5 22h54"/><circle cx="49" cy="17" r="2"/><path d="M43 22c2-3 4-5 6-5" opacity=".5"/></svg>',pluto:'<svg viewBox="0 0 64 32"><path d="M47 24A18 11 0 1 1 49 10"/><circle cx="49" cy="10" r="2"/></svg>'};
const cardImages={
sol:{src:'images/sol-luz.webp',alt:'La primera luz dorada de una estrella revelando lentamente la oscuridad del universo'},
venus:{src:'images/venus-esencia.webp',alt:'Flores amarillas silvestres bajo una luz dorada y tranquila'},
tierra:{src:'images/tierra-coincidir.webp',alt:'Dos caminos naturales que se encuentran en un paisaje al atardecer'},
marte:{src:'images/marte-fuerza.webp',alt:'Una flor amarilla creciendo entre rocas oscuras'},
saturno:{src:'images/saturno-recuerdos.webp',alt:'Recuerdos de paisajes, flores y momentos orbitando alrededor de Saturno'},
neptuno:{src:'images/neptuno-futuro.webp',alt:'Un horizonte nocturno azul con una luz dorada en la distancia'}
};
function show(w){if(!active||w.hidden||moonActive)return;selected=w;document.querySelector('#worldKicker').textContent=w.theme;document.querySelector('#worldTitle').textContent=w.name;document.querySelector('#worldText').textContent=w.text;document.querySelector('#worldSubtext').textContent=w.subtext||'';document.querySelector('#worldOrnament').innerHTML=ornaments[w.id]||'';let image=cardImages[w.id],slots=document.querySelector('#photoSlots');slots.innerHTML=image?`<figure class="narrative-image${w.id==='sol'?' sun-light-image':''}"><img src="${image.src}" alt="${image.alt}" width="1200" height="675" loading="eager" decoding="async"></figure>`:'';let cardImage=slots.querySelector('img');if(cardImage)cardImage.addEventListener('error',()=>slots.replaceChildren(),{once:true});panel.hidden=false;let next=nextWorld(w.id);document.querySelector('#return').textContent=w.id==='pluto'?'COMENZAR EL FINAL':next?`VIAJAR A ${next.name}`:'DESCUBRIR EL ÚLTIMO MUNDO'}
document.querySelector('#return').onclick=()=>{let completed=selected;if(completed?.id==='pluto'){panel.hidden=true;beginEnd();return}if(completed&&mainWorlds.includes(completed.id))visited.add(completed.id);updateProgress();if(!plutoReady&&mainWorlds.every(id=>visited.has(id))){panel.hidden=true;selected=null;unlockPluto();return}let next=nextWorld();panel.hidden=true;selected=null;if(next)setTimeout(()=>show(next),420)};document.querySelector('#goPluto').onclick=()=>{secret.hidden=true;show(pluto)};
document.querySelector('#closePanel').onclick=()=>{panel.hidden=true;selected=null};
function openMoon(){if(!active||moonActive||moonReturning||ending||!final.hidden)return;moonState={camera:camera.position.clone(),target:target.clone(),panelOpen:!panel.hidden};panel.hidden=true;moonActive=true;if(moonHalo)moonHalo.material.opacity=.16;app.classList.add('moon-mode');lunarSecret.hidden=false;setTimeout(()=>lunarSecret.classList.add('revealed'),620)}
document.querySelector('#closeLunar').onclick=()=>{if(!moonActive)return;lunarSecret.classList.remove('revealed');app.classList.remove('moon-mode');if(moonHalo)moonHalo.material.opacity=0;moonActive=false;moonReturning=true;setTimeout(()=>{lunarSecret.hidden=true},760)};
function beginEnd(){ending=true;selected=null;const detonate=()=>{supernova.hidden=false;supernova.querySelector('.nova-particles').innerHTML=Array.from({length:88},(_,i)=>`<i class="${i%5===0?'petal':'spark'}" style="--a:${i*4.09}deg;--d:${95+Math.random()*76}vmax;--t:${.7+Math.random()*1.7}s"></i>`).join('');requestAnimationFrame(()=>supernova.classList.add('run'));setTimeout(()=>{final.hidden=false;fade(.16,2500)},4400)};if(Number.isFinite(MUSIC_CONFIG.supernovaTimestamp)&&!audio.paused){let remaining=MUSIC_CONFIG.supernovaTimestamp-audio.currentTime;setTimeout(detonate,Math.max(0,remaining*1000))}else detonate()}document.querySelector('#restart').onclick=()=>{final.classList.add('reborn');supernova.hidden=false;supernova.classList.remove('run');requestAnimationFrame(()=>supernova.classList.add('rebirth'));setTimeout(()=>location.reload(),1700)};
let target=new THREE.Vector3(0,0,0),drag=false,lastX=0,downX=0,downY=0,moved=false;canvas.addEventListener('pointerdown',e=>{drag=true;moved=false;downX=e.clientX;downY=e.clientY;lastX=e.clientX});canvas.addEventListener('pointermove',e=>{if(drag){if(Math.hypot(e.clientX-downX,e.clientY-downY)>7)moved=true;if(!moonActive)solar.rotation.y+=(e.clientX-lastX)*.006;lastX=e.clientX}});canvas.addEventListener('pointercancel',()=>{drag=false;moved=false});canvas.addEventListener('pointerup',e=>{drag=false;if(moved||moonActive||moonReturning)return;pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;ray.setFromCamera(pointer,camera);if(moonHit&&ray.intersectObject(moonHit,true).length){openMoon();return}let h=ray.intersectObjects(worlds.filter(w=>!w.hidden).map(w=>w.mesh),true)[0];if(h){let w=worlds.find(x=>x.mesh===h.object||x.mesh.children.includes(h.object));if(w)show(w)}});
const focusVector=new THREE.Vector3(),directionVector=new THREE.Vector3(),desiredVector=new THREE.Vector3(),focusTargetVector=new THREE.Vector3(),projectedVector=new THREE.Vector3(),endingScale=new THREE.Vector3(1.15,1.15,1.15),homeCamera=new THREE.Vector3(0,18,64);
function animate(t){requestAnimationFrame(animate);if(document.hidden||(compactScreen&&t-lastRender<22))return;lastRender=t;if(!moonActive)worlds.forEach(w=>{if(w.id==='sol'){w.mesh.rotation.y+=.002;return}w.angle+=.00055/(w.r*.13);w.mesh.position.set(Math.cos(w.angle)*w.r,Math.sin(w.angle*1.7)*.45,Math.sin(w.angle)*w.r);w.mesh.rotation.y+=.004;if(w.moonOrbit)w.moonOrbit.rotation.y+=.012});orbitLines.forEach(line=>line.visible=!selected&&!moonActive);focusVector.set(0,0,0);if(moonActive&&moonMesh){moonMesh.getWorldPosition(focusVector);directionVector.copy(camera.position).sub(focusVector).normalize();desiredVector.copy(focusVector).add(directionVector.multiplyScalar(compactScreen?5.2:4.2));desiredVector.y+=.45;camera.position.lerp(desiredVector,.018);target.lerp(focusVector,.024)}else if(moonReturning&&moonState){camera.position.lerp(moonState.camera,.035);target.lerp(moonState.target,.04);if(camera.position.distanceTo(moonState.camera)<.04&&target.distanceTo(moonState.target)<.04){camera.position.copy(moonState.camera);target.copy(moonState.target);moonReturning=false;if(moonState.panelOpen)panel.hidden=false;moonState=null}}else{if(selected)selected.mesh.getWorldPosition(focusVector);let distance=selected?Math.max(selected.size*(compactScreen?7.1:5.7),compactScreen?15:12):64;if(selected?.id==='sol')desiredVector.set(0,compactScreen?10:8,compactScreen?34:29);else if(selected){directionVector.copy(focusVector).normalize().multiplyScalar(distance);desiredVector.copy(focusVector).add(directionVector);desiredVector.y+=distance*.24}else desiredVector.copy(homeCamera);camera.position.lerp(desiredVector,.022);if(selected)focusTargetVector.copy(focusVector);else focusTargetVector.set(0,0,0);if(selected&&compactScreen)focusTargetVector.y-=1.7;target.lerp(focusTargetVector,.03)}camera.lookAt(target);renderer.toneMappingExposure+=((moonActive?.78:1.12)-renderer.toneMappingExposure)*.035;worlds[0].mesh.getWorldPosition(focusVector);sunLight.position.copy(focusVector);if(!compactScreen)worlds.filter(w=>!w.hidden).forEach(w=>{let el=labels.querySelector(`[data-id="${w.id}"]`);if(!el)return;w.mesh.getWorldPosition(projectedVector).project(camera);el.style.left=`${(projectedVector.x*.5+.5)*100}%`;el.style.top=`${(-projectedVector.y*.5+.5)*100}%`;el.style.opacity=active&&!moonActive?'1':'0'});if(ending)solar.scale.lerp(endingScale,.008);renderer.render(scene,camera)}animate();
let resizeFrame=0;function resizeRenderer(){resizeFrame=0;compactScreen=screenQuery.matches;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,compactScreen?1.2:1.6));renderer.setSize(innerWidth,innerHeight,false)}function requestResize(){if(!resizeFrame)resizeFrame=requestAnimationFrame(resizeRenderer)}addEventListener('resize',requestResize,{passive:true});if('visualViewport'in window)window.visualViewport.addEventListener('resize',requestResize,{passive:true});updateProgress();setMusic();
